require_relative 'fictive/version'
require_relative 'fictive/story'
require_relative 'fictive/choice'
require_relative 'fictive/scene'
require_relative 'fictive/syntax'
require_relative 'fictive/text/compiler'
