require 'pathname'
require 'mementus'

require 'fictive/version'
require 'fictive/bundle'
require 'fictive/document'
require 'fictive/story'
require 'fictive/choice'
require 'fictive/passage'
require 'fictive/syntax'
require 'fictive/text/compiler'
require 'fictive/text/node'
require 'fictive/text/text_node'
require 'fictive/text/reference_node'
require 'fictive/text/conditional_node'
require 'fictive/text/expression_node'
require 'fictive/text/true_node'
require 'fictive/text/false_node'
